---
title: "lab06"
author: "yutian"
date: "9/28/2022"
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE, include  = FALSE)
```

```{r library}
library(tidytext)
library(tidyverse)
library(data.table)
library(dtplyr)
library(dplyr)
library(tibble)
```

## Step1. Read in the Data

Download and read it 
```{r}
if(!file.exists('mtsamples.csv'))
download.file("https://raw.githubusercontent.com/USCbiostats/data-science-data/master/00_mtsamples/mtsamples.csv", "mtsamples.csv", method="libcurl", timeout = 60)
mts <- read_csv("mtsamples.csv")
# change the data frame to tibble

mts <- as_tibble(mts)
mts
```


##  Question 1: What specialties do we have?

We can use count() from dplyr to figure out how many different catagories do we have? Are these catagories related? overlapping? evenly distributed?


```{r}
specialties <- 
  mts %>% count(medical_specialty)

specialties %>%
  arrange(desc(n)) %>%
knitr::kable()
```

```{r}

```

